import type { Metadata } from "next";
import { Jost, Montserrat } from "next/font/google";
import "@/global.css"

const jost = Jost({
  variable: "--font-jost-sans",
  subsets: ["latin"],
});

const montSerrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${jost.variable} ${montSerrat.variable}`}>
        {children}
      </body>
    </html>
  );
}
